---
# roles/nginx/tasks/main.yml
- name: Install Nginx repository
  apt_repository:
    repo: ppa:ondrej/nginx
    state: present

- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: true

- name: Remove Nginx default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - Restart Nginx